version: "2"
services:
  zoho-integration-api:
    container_name: selfcare
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      integration-db
  integration-db:
    container_name: integration-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
